name: "product"

models:
    originalModel: "product.json"
    enhancedModel: "product.yaml"

templates:
    components:
        - action
        - list
        - details
        - edit
    componentsOutDir: client/src/app/modules/catalog/

    files:
        - name: entity
          outDir: server/entities"

        - name: model
          outDir: client/src/app/models
          outFileName: "{name}.interface.ts"

        - name: service
          outDir: client/src/app/models

    exclude:
        components:
            - list
            - entity
        classes: 
            
            
