name: "product"
models:
    originalModel: "product.json"
    enhancedModel: "product.yaml"
templates:
    components:
        - action
        - list
        - details
        - edit
    componentsOutput: client/src/app/modules/catalog/
    
    classes:
        - name: entity 
          outputFolder: server/entities"
        - name: model 
          outputFolder: client/src/app/models
        - name: service 
          outputFolder: client/src/app/models

    exclude: 
        - list 
        - entity
